# Parameters for the model_crane environment

# Add the file_directory of input poitcloud folder 
file_directory: /home/aisl2/catkin_ws/src/latest_crane/map_optimization/input_pointcloud_data/gazebo_construction_env/


# Parameters for ground_plane
ground_angle_degree: 2.0
ground_distance_threshold: 0.1
min_ground_plane_size: 200499
ground_plane_cluster_Tolerance: 1.5  # Adjust this value based on the density of your point cloud
ground_plane_cluster_extraction: True 

# Parameters for wall_plane
wall_distance_threshold: 0.3
wall_angle_degree: 0.1
min_wall_plane_size: 2000
wall_plane_cluster_Tolerance: 1.5 # use large value if you donot want to do clustering on the  extracted wall plan

# Euclidean Cluster Extraction parameters
min_wall_segment_cluster_size: 1000     # Minimum number of points that a cluster should have
max_wall_segment_cluster_size: 25000000   # Maximum number of points that a cluster should have
wall_segment_cluster_Tolerance: 3.5   # Tolerance or maximum distance allowed between points in the same cluster during the Euclidean clustering process.
extract_largest_wall_cluster: true # do you want to want to find the largest cluster of  extracted wall plan