marvin:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    base_to_laser_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: scan_joint
        pid: {p: 1.1, i: 1.0, d: 1.0}